coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "packages/*/dist/**"
  - "packages/*/node_modules/**"
  - "packages/*/tests/**"
  - "**/coverage/**"
  - "**/*.d.ts"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
